"""Deny-by-default public projection rules for local presentation adapters."""

from __future__ import annotations

from dataclasses import fields, is_dataclass
from enum import Enum
from pathlib import Path
from typing import Any

from models import NormalizedEvent, ToolExecutionSummary
from utils import redact_sensitive


MAX_PUBLIC_STRING = 2048
MAX_PUBLIC_COLLECTION = 4096

# Adding a domain dataclass field does not change a public schema. Each field must
# be reviewed and added here deliberately.
PUBLIC_FIELDS_BY_TYPE: dict[str, tuple[str, ...]] = {
    "AdapterResult": (
        "status",
        "source",
        "observed_at",
        "error_code",
        "partial_count",
        "complete",
    ),
    "AxisCompleteness": (
        "axis",
        "complete",
        "confidence",
        "reason",
        "baseline_kind",
        "baseline_at",
        "evidence",
    ),
    "AgentNode": (
        "thread_id",
        "parent_thread_id",
        "agent_path",
        "nickname",
        "role",
        "model",
        "reasoning_effort",
        "status",
        "spawned_at",
        "updated_at",
        "interaction_count",
        "interaction_seconds",
        "wait_count",
        "wait_seconds",
        "resume_count",
        "resume_seconds",
        "close_count",
        "close_seconds",
        "error",
        "provenance",
        "children",
    ),
    "AlertOccurrence": (
        "id",
        "kind",
        "severity",
        "status",
        "reason",
        "opened_at",
        "updated_at",
        "escalated_at",
        "acknowledged_at",
        "resolved_at",
        "transitions",
    ),
    "AlertTransition": ("status", "timestamp", "reason"),
    "AttentionRequest": (
        "state",
        "request_id",
        "call_id",
        "turn_id",
        "summary",
        "detail",
        "started_at",
        "observed_at",
        "provenance",
    ),
    "CapabilityStatus": ("mode", "source", "confidence"),
    "ClockAssessment": (
        "source",
        "clock_domain",
        "source_timestamp",
        "observed_at",
        "adjudicated_at",
        "reason",
    ),
    "CodexPaths": (
        "codex_home",
        "sqlite_home",
        "state_db",
        "log_db",
        "session_index",
        "sessions_dir",
    ),
    "CollectorHealth": (
        "name",
        "duration_seconds",
        "last_success_at",
        "stale_age_seconds",
        "consecutive_failures",
        "error",
        "budget_exceeded",
        "command",
    ),
    "ObserverHealth": (
        "sample_kind",
        "scheduled_at",
        "started_at",
        "completed_at",
        "duration_seconds",
        "scheduling_lag_seconds",
        "event_loop_lag_seconds",
        "snapshot_age_seconds",
        "worker_in_flight_age_seconds",
        "last_success_at",
        "skipped_ticks",
        "coalesced_ticks",
        "consecutive_overdue",
        "degraded",
        "reason",
    ),
    "CommandExecutionSummary": (
        "command_name",
        "complete",
        "reason",
        "exit_code",
        "duration_seconds",
        "stdout_bytes_read",
        "stdout_bytes_retained",
        "stdout_bytes_filtered",
        "stderr_bytes_read",
        "stderr_bytes_retained",
        "stdout_lines_read",
        "stderr_lines_read",
        "records_retained",
        "records_filtered",
        "records_dropped",
    ),
    "CompactSourceStatus": (
        "configured",
        "readable",
        "source",
        "last_probe_at",
        "last_event_at",
        "error",
        "bytes_read",
        "consumed_bytes",
        "record_count",
        "backlog_bytes",
        "backlog_records_lower_bound",
        "backlog_age_seconds",
        "budget_exceeded",
        "oversize_record_count",
        "skipped_bytes",
        "gap_count",
        "gap_reason",
        "gap_hash",
        "parse_duration_seconds",
        "device",
        "inode",
        "generation",
        "anchor_hash",
        "stream_uncertain",
        "stream_uncertainty_count",
        "stream_uncertainty_reason",
        "parse_validity",
        "source_authenticity",
        "identity_binding",
        "semantic_confidence",
        "binding_evidence",
    ),
    "CompactionEvidence": (
        "edge",
        "timestamp",
        "source",
        "observed_at",
        "confidence",
        "direct",
        "detail",
        "parse_validity",
        "source_authenticity",
        "identity_binding",
        "semantic_confidence",
        "binding_evidence",
    ),
    "CompactionSummary": (
        "operation_id",
        "status",
        "requested_at",
        "started_at",
        "completed_at",
        "failed_at",
        "aborted_at",
        "trigger",
        "context_tokens",
        "context_tokens_after",
        "context_window",
        "auto_compact_token_limit",
        "turn_id",
        "source",
        "confidence",
        "reconstructed",
        "retry_count",
        "failure",
        "evidence",
    ),
    "ConnectionAssessment": (
        "key",
        "state",
        "local",
        "peer",
        "route",
        "recv_q",
        "send_q",
        "sent_delta",
        "received_delta",
        "acked_delta",
        "retrans_delta",
        "idle_seconds",
        "health",
        "reason",
        "tls_server_name",
        "tls_alpn_protocols",
        "tls_versions",
        "tls_observed_at",
    ),
    "CurrentOperationSummary": (
        "category",
        "label",
        "detail",
        "started_at",
        "tool_count",
        "file_count",
        "agent",
        "provenance",
    ),
    "DiagnosisFinding": (
        "severity",
        "conclusion",
        "reason",
        "evidence",
        "provenance",
        "freshness_seconds",
        "action",
    ),
    "DiscoveryCandidateDiagnostic": ("pid", "command", "role", "outcome", "reason", "confidence"),
    "DiscoverySummary": (
        "candidates",
        "confirmed",
        "rejected",
        "unresolved",
        "diagnostics",
        "labeled_true_positive",
        "labeled_false_positive",
        "labeled_false_negative",
        "precision",
        "recall",
    ),
    "Diagnostic": (
        "code",
        "severity",
        "domain",
        "source",
        "observed_at",
        "privacy_class",
        "parameters",
        "message_key",
        "recovery_state",
    ),
    "DiagnosticParameter": ("name", "value"),
    "EvidenceObservation": (
        "source",
        "observed_from",
        "observed_to",
        "sample_generation",
        "valid_through",
        "stale_age_seconds",
        "complete",
    ),
    "SnapshotTemporalCut": (
        "kind",
        "sample_generation",
        "observed_from",
        "observed_to",
        "max_source_skew_seconds",
        "actual_source_skew_seconds",
        "coherent",
        "reason",
        "sources",
    ),
    "EventTelemetrySummary": (
        "total_events",
        "observed_events",
        "unparsed_events",
        "unknown_rate",
        "observation_p50_seconds",
        "observation_p95_seconds",
        "rendered_events",
        "render_p50_seconds",
        "render_p95_seconds",
        "dedupe_filter_bits_set",
        "dedupe_filter_capacity_bits",
        "dedupe_filter_fill_ratio",
        "dedupe_filter_matches",
        "dedupe_filter_degraded_drops",
        "dedupe_filter_degraded",
        "stale_stream_generation_dropped",
        "stream_identity_limit_dropped",
        "stream_generation_advances",
    ),
    "FailureInfo": ("category", "message", "additional_details", "turn_id", "timestamp", "source"),
    "HistoryPersistenceStatus": (
        "enabled",
        "queue_depth",
        "queue_capacity",
        "enqueued_samples",
        "persisted_samples",
        "dropped_samples",
        "coalesced_samples",
        "last_persisted_sample_at",
        "last_success_at",
        "stats_generated_at",
        "stats_age_seconds",
        "writer_lag_seconds",
        "consecutive_failures",
        "error",
        "maintenance_error",
        "shutdown_timed_out",
        "shared_path_policy",
    ),
    "HistoryWindowStats": (
        "label",
        "window_seconds",
        "sample_count",
        "turn_count",
        "failure_count",
        "failure_rate",
        "ttft_samples",
        "ttft_p50_seconds",
        "ttft_p95_seconds",
        "tool_samples",
        "tool_p50_seconds",
        "tool_p95_seconds",
        "reconnect_count",
        "fallback_count",
        "recovery_samples",
        "recovery_average_seconds",
        "compact_count",
        "compact_per_hour",
        "silence_samples",
        "silence_p50_seconds",
        "silence_p95_seconds",
        "compact_manual_count",
        "compact_auto_count",
        "compact_failure_count",
        "compact_retry_count",
        "compact_duration_samples",
        "compact_duration_p50_seconds",
        "compact_duration_p95_seconds",
        "compact_context_samples",
        "compact_context_before_average",
        "compact_context_after_average",
        "phase_duration_seconds",
        "waiting_upstream_seconds",
        "attention_wait_seconds",
        "observer_blind_samples",
        "observer_blind_frequency",
        "protocol_degraded_samples",
        "protocol_degraded_frequency",
    ),
    "InstanceSnapshot": (
        "instance_id",
        "paths",
        "display_codex_home",
        "display_sqlite_home",
        "discovery_method",
        "capabilities",
        "protocol_capabilities",
        "collector_health",
        "adapter_results",
        "diagnostics",
        "unknown_event_types",
        "protocol_shape_families",
        "protocol_family_counters",
        "rollout_context_truncated",
        "rollout_activity",
        "process_data_stale_age_seconds",
        "socket_data_stale_age_seconds",
        "auto_compact_token_limit",
        "auto_compact_token_limit_scope",
        "compact_prompt_overridden",
        "auto_compact_config_source",
        "history_windows",
        "tui_session_log",
        "hook_events",
        "processes",
        "sessions",
    ),
    "NetworkEvidence": ("state", "reason", "stale", "stale_age_seconds", "connections"),
    "NormalizedEvent": (
        "timestamp",
        "kind",
        "summary",
        "detail",
        "source",
        "confidence",
        "turn_id",
        "source_id",
        "failure",
        "derived",
        "complete",
        "metadata",
        "observed_at",
        "rendered_at",
        "unparsed",
        "source_timestamp",
        "adjudicated_at",
        "clock_domain",
        "clock_trust",
        "clock_uncertain",
        "clock_reason",
        "clock_sequence",
        "parse_validity",
        "source_authenticity",
        "identity_binding",
        "semantic_confidence",
        "binding_evidence",
    ),
    "ObservationPulse": (
        "sampled_at",
        "turn_started_at",
        "phase_started_at",
        "last_transition_at",
        "last_semantic_at",
        "last_semantic_kind",
        "last_semantic_source",
        "last_rollout_growth_at",
        "last_process_activity_at",
        "last_network_progress_at",
        "last_log_activity_at",
        "last_evidence_at",
        "last_evidence_source",
        "last_evidence_detail",
        "last_probe_at",
        "rollout_probe_at",
        "process_probe_at",
        "network_probe_at",
        "log_probe_at",
        "rollout_partial_bytes",
        "rollout_bytes_delta",
        "process_activity",
        "network_bytes_delta",
        "quiet_full_samples",
        "collector_stale",
        "collector_stale_reason",
        "auto_compact_expected",
        "auto_compact_reason",
        "silence_baseline_samples",
        "silence_p50_seconds",
        "silence_p95_seconds",
    ),
    "ProcessIdentity": ("pid", "start_time"),
    "ProcessInfo": (
        "identity",
        "ppid",
        "command",
        "elapsed_seconds",
        "cpu_percent",
        "process_state",
        "wait_channel",
        "args",
        "role",
        "cwd",
        "instance_id",
        "discovery_method",
        "session_id",
        "session_title",
        "current_task",
        "model",
        "reasoning_effort",
        "rollout_path",
        "activity",
        "process_group_id",
        "foreground_process_group_id",
        "terminal",
        "discovery_confidence",
        "discovery_evidence",
    ),
    "ProcessTreeActivity": (
        "available",
        "sampled_at",
        "cpu_seconds_delta",
        "io_bytes_delta",
        "io_operations_delta",
        "context_switches_delta",
        "thread_count",
        "child_count",
        "children_created",
        "children_exited",
        "child_state_changes",
        "active",
        "detail",
        "children",
    ),
    "ChildProcessActivity": (
        "identity",
        "parent_pid",
        "command",
        "state",
        "elapsed_seconds",
        "cpu_seconds_delta",
        "io_bytes_delta",
        "io_operations_delta",
        "context_switches_delta",
        "active",
    ),
    "ProtocolCapabilities": (
        "turn_timing",
        "item_timing",
        "tool_timing",
        "token_usage",
        "rate_limits",
        "collab_status",
        "subagent_path",
        "action_required",
    ),
    "Provenance": ("source", "confidence", "derived", "complete"),
    "RateLimitSummary": (
        "primary",
        "secondary",
        "credits",
        "has_credits",
        "reached",
        "reason",
        "provenance",
    ),
    "RateLimitWindow": ("used_percent", "reset_at", "window_minutes"),
    "SessionHealth": (
        "instance_id",
        "session_id",
        "process",
        "lifecycle",
        "lifecycle_confidence",
        "lifecycle_provenance",
        "recovery",
        "attention",
        "attention_confidence",
        "attention_provenance",
        "attention_request",
        "protocol_uncertain",
        "protocol_uncertainty_scope",
        "protocol_uncertainty_reason",
        "clock_uncertain",
        "clock_assessments",
        "completeness",
        "current_operation",
        "diagnosis",
        "event_telemetry",
        "observation",
        "silence",
        "network",
        "phase",
        "phase_since",
        "alert",
        "alert_level",
        "alert_reason",
        "alert_age_seconds",
        "alerts",
        "current_failure",
        "latest_failure",
        "token_used",
        "token_limit",
        "token_usage",
        "cumulative_token_usage",
        "rate_limits",
        "turns",
        "compactions",
        "tool_executions",
        "terminal_sessions",
        "terminal_association",
        "agents",
        "protocol_capabilities",
        "process_exited",
        "process_exited_at",
        "events",
    ),
    "SessionCompleteness": (
        "lifecycle",
        "attention",
        "failure_recovery",
        "terminal_ownership",
        "network",
        "silence",
    ),
    "SilenceAssessment": (
        "state",
        "reason",
        "assessed_at",
        "silence_started_at",
        "evidence_at",
        "severity",
        "provenance",
    ),
    "SourceCapabilities": ("threads", "rollout_path", "logs", "thread_id", "process_uuid"),
    "TerminalAssociationSummary": (
        "eligible_operations",
        "associated_operations",
        "confirmed",
        "ambiguous",
        "conflicting",
        "unresolved",
        "dropped",
        "reasons",
        "labeled_correct",
        "labeled_incorrect",
        "association_coverage",
        "unresolved_rate",
        "precision",
        "private_state_entries",
        "private_state_estimated_bytes",
        "private_state_evictions",
        "private_state_dropped",
        "private_state_recoveries",
        "private_state_reasons",
    ),
    "TerminalSessionSummary": (
        "terminal_id",
        "root_call_id",
        "process_id",
        "turn_id",
        "command",
        "cwd",
        "status",
        "exit_code",
        "capability",
        "started_at",
        "completed_at",
        "last_output_at",
        "retained_bytes",
        "dropped_bytes",
        "upstream_truncated",
        "stale",
        "process_active",
        "source",
        "association_status",
        "correlation_source",
        "association_reason",
    ),
    "TokenUsageSummary": (
        "input_tokens",
        "cached_input_tokens",
        "output_tokens",
        "reasoning_output_tokens",
        "total_tokens",
        "context_tokens",
        "context_window",
        "provenance",
    ),
    "ToolExecutionSummary": (
        "call_id",
        "turn_id",
        "category",
        "display_name",
        "tool_name",
        "started_at",
        "completed_at",
        "duration_seconds",
        "status",
        "exit_code",
        "completion_status",
        "command",
        "cwd",
        "arguments",
        "output",
        "files",
        "provenance",
    ),
    "TurnSummary": (
        "turn_id",
        "started_at",
        "completed_at",
        "duration_seconds",
        "time_to_first_token_seconds",
        "status",
        "result",
        "model",
        "reasoning_effort",
        "collaboration_mode",
        "trace_id",
        "token_usage",
        "tool_count",
        "tool_duration_seconds",
        "longest_tool",
        "reconnect_count",
        "fallback_count",
        "recovery_duration_seconds",
        "compact_count",
        "failure",
        "tools",
        "provenance",
    ),
    "UnparsedPayload": ("source_type", "length", "sha256", "truncated"),
}

EVENT_METADATA_FIELDS = frozenset(
    {
        "attention_state",
        "category",
        "command",
        "completion_status",
        "context_tokens",
        "context_tokens_after",
        "context_window",
        "cwd",
        "duration_seconds",
        "edge",
        "exit_code",
        "files",
        "invocation",
        "model",
        "operation_id",
        "phase",
        "process_id",
        "reasoning_effort",
        "retry_count",
        "semantic_scope",
        "status",
        "tool_count",
        "tool_name",
        "trigger",
    }
)
ROLLOUT_ACTIVITY_FIELDS = frozenset(
    {
        "actual_bytes_read",
        "anchor_hash",
        "backlog_age_seconds",
        "backlog_bytes",
        "backlog_records_lower_bound",
        "bootstrap_truncated",
        "budget_exceeded",
        "consumed_bytes",
        "device",
        "file_size",
        "gap_count",
        "gap_hash",
        "gap_reason",
        "generation",
        "inode",
        "metadata_backfill_dropped",
        "metadata_backfill_reason",
        "oversize_record_count",
        "parse_duration_seconds",
        "parser_evictions",
        "path",
        "processed_records",
        "record_count",
        "skipped_bytes",
        "source_bytes",
        "stream_uncertain",
        "stream_uncertainty_count",
        "stream_uncertainty_reason",
    }
)


def _bounded_string(value: str) -> str:
    redacted = redact_sensitive(value)
    if len(redacted) <= MAX_PUBLIC_STRING:
        return redacted
    return redacted[:MAX_PUBLIC_STRING] + "...[truncated]"


def _event_metadata(value: object) -> dict[str, Any]:
    if not isinstance(value, dict):
        return {}
    return {
        str(key): public_value(item)
        for key, item in value.items()
        if str(key) in EVENT_METADATA_FIELDS
    }


def _rollout_activity(value: object) -> list[dict[str, Any]]:
    if not isinstance(value, (list, tuple)):
        return []
    return [
        {
            str(key): public_value(item)
            for key, item in row.items()
            if str(key) in ROLLOUT_ACTIVITY_FIELDS
        }
        for row in value[:MAX_PUBLIC_COLLECTION]
        if isinstance(row, dict)
    ]


def public_rollout_activity(value: object) -> list[dict[str, Any]]:
    return _rollout_activity(value)


def public_value(value: Any) -> Any:
    """Project a value through explicit public fields and bounded redaction."""

    if isinstance(value, Enum):
        return value.value
    if isinstance(value, Path):
        return _bounded_string(str(value))
    if isinstance(value, str):
        return _bounded_string(value)
    if is_dataclass(value):
        type_name = type(value).__name__
        allowed = PUBLIC_FIELDS_BY_TYPE.get(type_name)
        if allowed is None:
            return {}
        available = {item.name for item in fields(value)}
        projected: dict[str, Any] = {}
        for name in allowed:
            if name not in available:
                continue
            item = getattr(value, name)
            if isinstance(value, NormalizedEvent) and name == "metadata":
                projected[name] = _event_metadata(item)
            elif type_name == "InstanceSnapshot" and name == "rollout_activity":
                projected[name] = _rollout_activity(item)
            elif type_name == "InstanceSnapshot" and name == "diagnostics":
                from diagnostics import normalize_diagnostic

                projected[name] = public_value(
                    tuple(normalize_diagnostic(entry, source="instance") for entry in item)
                )
            elif isinstance(value, ToolExecutionSummary) and name == "output":
                projected[name] = None
            else:
                projected[name] = public_value(item)
        return projected
    if isinstance(value, dict):
        return {
            _bounded_string(str(key)): public_value(item)
            for key, item in list(value.items())[:MAX_PUBLIC_COLLECTION]
        }
    if isinstance(value, (list, tuple)):
        return [public_value(item) for item in value[:MAX_PUBLIC_COLLECTION]]
    return value
