"""Shared hard limits for incremental JSONL evidence readers."""

MAX_INGRESS_BYTES_PER_TICK = 512 * 1024
MAX_INGRESS_RECORDS_PER_TICK = 512
MAX_INGRESS_PARSE_SECONDS = 0.05
MAX_JSONL_RECORD_BYTES = 256 * 1024
